### PR TITLE
Switched to imapclient, logging and refactoring for resilience

### PR DESCRIPTION
**Pull request by andyloree**
Fairly large refactoring.  I was getting regular EOF termination exceptions from the prior version, as well as upon restart, there was no check for unread mail that might have arrived while not running.

Upon investigating the cause/reading IMAP RFC's for idle mode, I came across the [imapclient](https://github.com/mjs/imapclient), which has built-in idle mode looping.

Full list of enhancements for your consideration :
- Switched to imapclient for all email functionality including IDLE wait notification - default behavior is every 5 minutes we terminate the idle loop (configurable via settings)
- Simplified imap connections to be minimal and restartable - the ```Imap`` class now keeps a single IMAP connection, switching into and out of IDLE mode as needed, querying unread, marking read etc, and also closing the connection in a timely fashion
- Use python's [logging](https://docs.python.org/3/howto/logging.html) facility - no longer using ```print()``` calls, now consistent logging across classes,  Verbosity is globally controlled via logging setLevel, so settings do not need to be passed around as well
- ```namedtuple()``` data structures and separation of concerns refactoring - Separated out ```Rules``` class to process a ```EmailStruct``` namedtuple() collections, returning ```MatchResult``` collection.

Issues resolved by this PR:
- Fatal terminations on prior IDLE loop processing would stop the application
- Upon startup, existing unread mail was not queried/processed through our rules.  This change now always queries unread messages as part of the overall loop every IDLE timeout (default every 5 minutes) so worst-case delay in Gotify sending is minimized.
- Prior version incorrectly might mark messages as read even though a Gotify send failure occured (thus missing a message). During the final phase of sending messages, ```Gotify``` classes ```send()``` returns list of ```EmailStructs``` that were successfully sent to Gotify, and thus can safely be marked as read in IMAP.

I have not had time to add tests/mocks, hope to do so in a future PR.  I have been running this version for over a week, and have seen several timeout exceptions (e.g. network drop or IMAP server disconnected) and this new version continues to reconnect without issue of hanging and never missing or delaying a message.

### CODE REVIEW

**Comment by cyrinux** [comment]
Wow thanks @andyloree, tiny refactoring! Will try this quickly 😊
Thanks for the detailed changelog, I like the sound of this.

**Comment by cyrinux** [comment]
@andyloree can you dos2unix and push your `requirements.txt` ? Also I pip can't find freeze lib 🤔 404.
```
ERROR: Could not find a version that satisfies the requirement freeze==0.0.1 (from versions: none)
ERROR: No matching distribution found for freeze==0.0.1
```

**Comment by cyrinux** [comment]
@andyloree I took time to fix some little refactoring typos, and cleanup a little with the help of tox.
This seems to works well for me also like this.
Tell me if you are ok with those commit and will merge then.

**Comment by andyloree** [comment]
> 
> 
> @andyloree I took time to fix little refactoring typo, and cleanup a little with the help of tox.
> This seems to works well for me also like this.
> Tell me if you are ok with those commit and will merge then.

These look great, excellent catches and fixes.  I will try to setup some mocks/unit testing as well in the near future.  Thanks again

**Comment by cyrinux** [comment]
I merge this MR so 👍🏻

**Pull request merged**
